"""create route_details table

Revision ID: 2443c2d16c82
Revises: 8a1994d22157
Create Date: 2024-10-09 10:38:05.707823

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2443c2d16c82"
down_revision: Union[str, None] = "8a1994d22157"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "route_details",
        sa.Column("stop_number", sa.Integer(), nullable=False),
        sa.Column("route_id", sa.Integer(), nullable=False),
        sa.Column("stop_station_id", sa.Integer(), nullable=False),
        sa.Column("arrival_time", sa.TIMESTAMP(), nullable=True),
        sa.Column("departure_time", sa.TIMESTAMP(), nullable=True),
        sa.ForeignKeyConstraint(["route_id"], ["routes.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["stop_station_id"],
            ["stations.id"],
        ),
        sa.PrimaryKeyConstraint("stop_number", "route_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("route_details")
    # ### end Alembic commands ###
