"""create personnel table

Revision ID: 4c6da7939516
Revises: 8f0e61941c72
Create Date: 2024-10-08 23:09:23.639859

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4c6da7939516"
down_revision: Union[str, None] = "8f0e61941c72"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "personnel",
        sa.Column("person_tax_id", sa.CHAR(length=12), nullable=False),
        sa.Column("station_id", sa.Integer(), nullable=False),
        sa.Column("position_id", sa.Integer(), nullable=False),
        sa.Column("crew_id", sa.Integer(), nullable=False),
        sa.Column("full_name", sa.String(length=255), nullable=False),
        sa.CheckConstraint(
            "length(person_tax_id)=12", name="check_person_tax_id_length"
        ),
        sa.ForeignKeyConstraint(
            ["crew_id"],
            ["crew_directories.id"],
        ),
        sa.ForeignKeyConstraint(
            ["position_id"],
            ["positions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["station_id"], ["stations.id"], onupdate="CASCADE", ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("person_tax_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("personnel")
    # ### end Alembic commands ###
