"""Delete station_id foreign key.

Revision ID: 665cbad1038e
Revises: 4a662489f2ad
Create Date: 2024-10-08 21:07:14.430873

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "665cbad1038e"
down_revision: Union[str, None] = "4a662489f2ad"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("trains_station_id_fkey", "trains", type_="foreignkey")
    op.drop_column("trains", "station_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "trains",
        sa.Column("station_id", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.create_foreign_key(
        "trains_station_id_fkey",
        "trains",
        "stations",
        ["station_id"],
        ["id"],
        onupdate="CASCADE",
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###
