"""Create train_types table.

Revision ID: 7c6b586b5f55
Revises: cf7c943a2010
Create Date: 2024-09-30 10:49:42.531643

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7c6b586b5f55"
down_revision: Union[str, None] = "cf7c943a2010"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "train_types",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("type_name", sa.String(length=100), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("type_name"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("train_types")
    # ### end Alembic commands ###
