"""create routes table

Revision ID: 8a1994d22157
Revises: 4c6da7939516
Create Date: 2024-10-09 10:18:39.498644

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8a1994d22157"
down_revision: Union[str, None] = "4c6da7939516"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "routes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("train_id", sa.Integer(), nullable=False),
        sa.Column("crew_id", sa.Integer(), nullable=False),
        sa.Column("owner_station_id", sa.Integer(), nullable=False),
        sa.Column("departure_station_id", sa.Integer(), nullable=False),
        sa.Column("arrival_station_id", sa.Integer(), nullable=False),
        sa.Column("departure_time", sa.TIMESTAMP(), nullable=False),
        sa.Column("arrival_time", sa.TIMESTAMP(), nullable=False),
        sa.ForeignKeyConstraint(
            ["arrival_station_id"],
            ["stations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["crew_id"],
            ["crew_directories.id"],
        ),
        sa.ForeignKeyConstraint(
            ["departure_station_id"],
            ["stations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["owner_station_id"],
            ["stations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["train_id"],
            ["trains.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("routes")
    # ### end Alembic commands ###
