"""create crew_directories table

Revision ID: 8f0e61941c72
Revises: 60f66351e315
Create Date: 2024-10-08 22:35:09.998728

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8f0e61941c72"
down_revision: Union[str, None] = "60f66351e315"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "crew_directories",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("crew_name", sa.String(length=255), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("crew_name"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("crew_directories")
    # ### end Alembic commands ###
