"""Create stations table.

Revision ID: cf7c943a2010
Revises: 46314420cf85
Create Date: 2024-09-27 13:28:05.422661

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "cf7c943a2010"
down_revision: Union[str, None] = "46314420cf85"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "stations",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("tax_id", sa.CHAR(length=12), nullable=False),
        sa.Column("address_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.CheckConstraint("length(tax_id)=12", name="check_tax_id_length"),
        sa.ForeignKeyConstraint(["address_id"], ["addresses.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("address_id"),
        sa.UniqueConstraint("tax_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("stations")
    # ### end Alembic commands ###
