"""Updated the relationship between the trains and stations tables (many-to-many).

Revision ID: e8adec54cd87
Revises: d58957ea71ed
Create Date: 2024-10-04 13:00:14.269078

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e8adec54cd87"
down_revision: Union[str, None] = "d58957ea71ed"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "train_station",
        sa.Column("train_id", sa.Integer(), nullable=False),
        sa.Column("station_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["station_id"], ["stations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["train_id"], ["trains.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("train_id", "station_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("train_station")
    # ### end Alembic commands ###
